services:
    frontend:
      build:
        context: ./frontend
      image: tma-front
      container_name: tma_fcon
      networks:
        - tma-nw-b
      ports:
        - "3000:3000"
      depends_on: 
        - backend


    backend:
      build:
        context: ./backend
      image: tma-back
      container_name: tma_bcon
      networks:
        - tma-nw-b
      ports:
        - "5000:5000"
      depends_on: 
        -  mongodb


    nginx:
      build: ./nginx
      image: tma-nx
      container_name: tma_nxcon
      networks:
        - tma-nw-b
      ports:
        - "80:80"
      depends_on:
        - frontend


    mongodb:
      image: mongo:8.2
      container_name: mongodb_con
      volumes:
        - tma-data:/data/db
      networks:
        - tma-nw-b
      


networks:
  tma-nw-b:

volumes:
  tma-data:


