services:
    frontend:
      build:
        context: ./frontend
      image: tma-front
      container_name: tma_fcon
      networks:
        - tma-nw-b
      ports:
        - "3000:3000"
      depends_on: 
        - backend


    backend:
      build:
        context: ./backend
      image: tma-back
      container_name: tma_bcon
      env_file:
        - .env
      networks:
        - tma-nw-b
      ports:
        - "5000:5000"
      depends_on: 
        mongodb:
          condition: service_healthy


    nginx:
      build: ./nginx
      image: tma-nx
      container_name: tma_nxcon
      networks:
        - tma-nw-b
      ports:
        - "80:80"
      depends_on:
        - frontend


    mongodb:
      image: mongo:8.2
      container_name: mongodb_con
      env_file:
        - .env
      volumes:
        - tma-data:/data/db
      networks:
        - tma-nw-b
      healthcheck:
        test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping').ok", "--quiet"]
        interval: 10s
        timeout: 5s
        retries: 5    


networks:
  tma-nw-b:

volumes:
  tma-data:


